version: 2

sources:
  - name: staging
    database: flight-db-dwh
    schema: stg
    tables:
      - name: aircrafts_data
      - name: airports_data
      - name: boarding_passes
      - name: bookings
      - name: flights
      - name: seats
      - name: ticket_flights
      - name: tickets